#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using ThinkManage;


namespace ThinkManage	
{
	public partial class Category
	{
		private string _categoryName;
		public virtual string CategoryName 
		{ 
		    get
		    {
		        return this._categoryName;
		    }
		    set
		    {
		        this._categoryName = value;
		    }
		}
		
		private int _id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private int _pId;
		public virtual int PId 
		{ 
		    get
		    {
		        return this._pId;
		    }
		    set
		    {
		        this._pId = value;
		    }
		}
		
		private DateTime _dateCreated;
		public virtual DateTime DateCreated 
		{ 
		    get
		    {
		        return this._dateCreated;
		    }
		    set
		    {
		        this._dateCreated = value;
		    }
		}
		
		private int _id2;
		public virtual int Id2 
		{ 
		    get
		    {
		        return this._id2;
		    }
		    set
		    {
		        this._id2 = value;
		    }
		}
		
		private IList<ThinkContents> _thinkContents = new List<ThinkContents>();
		public virtual IList<ThinkContents> ThinkContents 
		{ 
		    get
		    {
		        return this._thinkContents;
		    }
		}
		
	}
}
