#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using ThinkManage;


namespace ThinkManage	
{
	public partial class ThinkManageEntitiesModel : OpenAccessContext, IThinkManageEntitiesModelUnitOfWork
	{
		private static string connectionStringName = @"";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
		
			
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntityDiagrams.rlinq");
	
		public ThinkManageEntitiesModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public ThinkManageEntitiesModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
	
		public ThinkManageEntitiesModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public ThinkManageEntitiesModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public ThinkManageEntitiesModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Category> Categories 
		{
	    	get
	    	{
	        	return this.GetAll<Category>();
	    	}
		}
		
		public IQueryable<Tag> Tags 
		{
	    	get
	    	{
	        	return this.GetAll<Tag>();
	    	}
		}
		
		public IQueryable<ThinkContents> ThinkContents 
		{
	    	get
	    	{
	        	return this.GetAll<ThinkContents>();
	    	}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "mssql";
			return backend;
		}
	}

	public interface IThinkManageEntitiesModelUnitOfWork : IUnitOfWork
	{
		IQueryable<Category> Categories 
		{ 
			get;
		}
		IQueryable<Tag> Tags 
		{ 
			get;
		}
		IQueryable<ThinkContents> ThinkContents 
		{ 
			get;
		}
	}
}
#pragma warning restore 1591

