#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using ThinkManage;


namespace ThinkManage	
{
	public partial class ThinkContents
	{
		private int _id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private int _categoryId;
		public virtual int CategoryId 
		{ 
		    get
		    {
		        return this._categoryId;
		    }
		    set
		    {
		        this._categoryId = value;
		    }
		}
		
		private int _tagId;
		public virtual int TagId 
		{ 
		    get
		    {
		        return this._tagId;
		    }
		    set
		    {
		        this._tagId = value;
		    }
		}
		
		private string _thinkContent;
		public virtual string ThinkContent 
		{ 
		    get
		    {
		        return this._thinkContent;
		    }
		    set
		    {
		        this._thinkContent = value;
		    }
		}
		
		private DateTime _dateCreated;
		public virtual DateTime DateCreated 
		{ 
		    get
		    {
		        return this._dateCreated;
		    }
		    set
		    {
		        this._dateCreated = value;
		    }
		}
		
		private Tag _tag;
		public virtual Tag Tag 
		{ 
		    get
		    {
		        return this._tag;
		    }
		    set
		    {
		        this._tag = value;
		    }
		}
		
		private Category _category;
		public virtual Category Category 
		{ 
		    get
		    {
		        return this._category;
		    }
		    set
		    {
		        this._category = value;
		    }
		}
		
	}
}
